defaults:
  - _self_
  #- dataset: cifar10(2025/07/18)
  - model: simplecnn #simplecnn→resnet
  - optimizer: adam
  - lr_scheduler: multi_step
seed: 50 #再現性確保のため、固定値を採用

dataloader: 
  batch_size: 64  # ← 256 から減らす（64：SimpleCNN、32：ResNet）(5月20日)
  num_workers: 2  # ← 16 から減らす
  pin_memory: true

epoch: 100 # 時間削減のため200→100へ変更
          #ResNetの際には、時間的考慮で20に変更
        #---データセットの指定---
dataset: #ここを修正する（2025/07/18）
  train:
    _target_: train_reg.EVLabelWrapper #train_reg.py内のクラスを指定
    annotation_file: "path/to/your/annotations.csv" # annotations.csvへのパス
    img_dir: "path/to/your/training_images"       # 学習用画像が保存されているフォルダへのパス

    transform:
    #データ拡張（6／15）
      random_resized_crop:
        size: 32 #モデルに合わせて調整（32×32）
      random_horizontal_flip: # ← これが左右反転です
        p: 0.5                # ← 50% の確率で反転
      random_vertical_crop: # 上下反転
        p: 0.5
      random_rotation: # 回転
        degrees: 15

      normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
  # 学習・検証データ分割の設定 (例: 全3640件を3000件の学習と640件の検証に分割)
  random_split:
    lengths: [3000, 640] #変更前lengths: [40000, 10000]
    
  #---Optuna1とHydraの設定---
optuna:
  direction: maximize
  n_trials: 100
  sampler:
    _target_: optuna.samplers.TPESampler
hydra:
  run:
    dir: ./
  output_subdir: null
  job_logging:
    version: 1
    handlers:
      console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
    root:
      handlers: [console]
    disable_existing_loggers: false