defaults:
  - _self_
  - dataset: cifar10
  - model: simplecnn #simplecnn→resnet
  - optimizer: adam
  - lr_scheduler: multi_step
seed: 50 #再現性確保のため、固定値を採用

dataloader: 
  batch_size: 64  # ← 256 から減らす（64：SimpleCNN、32：ResNet）(5月20日)
  num_workers: 4  # ← 16 から減らす
  pin_memory: true

epoch: 40 # 時間削減のため200→100へ変更
          #ResNetの際には、時間的考慮で20に変更
dataset:
  train:
    transform:
      random_resized_crop:
        size: 32
      random_horizontal_flip:
        p: 0.5
      normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
  random_split:
    lengths: [40000, 10000]
optuna:
  direction: maximize
  n_trials: 100
  sampler:
    _target_: optuna.samplers.TPESampler
hydra:
  run:
    dir: ./
  output_subdir: null
  job_logging:
    version: 1
    handlers:
      console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
    root:
      handlers: [console]
    disable_existing_loggers: false